#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

/* automatically generated by rust-bindgen */

pub const paFormatIsSupported: ::std::os::raw::c_uint = 0;
pub const paFramesPerBufferUnspecified: ::std::os::raw::c_uint = 0;
unsafe extern "C" {
    /** Retrieve the release number of the currently running PortAudio build.
 For example, for version "19.5.1" this will return 0x00130501.

 @see paMakeVersionNumber
*/
    pub fn Pa_GetVersion() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    /** Retrieve a textual description of the current PortAudio build,
 e.g. "PortAudio V19.5.0-devel, revision 1952M".
 The format of the text may change in the future. Do not try to parse the
 returned string.

 @deprecated As of 19.5.0, use Pa_GetVersionInfo()->versionText instead.
*/
    pub fn Pa_GetVersionText() -> *const ::std::os::raw::c_char;
}
/**
 A structure containing PortAudio API version information.
 @see Pa_GetVersionInfo, paMakeVersionNumber
 @version Available as of 19.5.0.
*/
#[repr(C)]
#[derive(Debug, Copy)]
pub struct PaVersionInfo {
    pub versionMajor: ::std::os::raw::c_int,
    pub versionMinor: ::std::os::raw::c_int,
    pub versionSubMinor: ::std::os::raw::c_int,
    /**
     This is currently the Git revision hash but may change in the future.
     The versionControlRevision is updated by running a script before compiling the library.
     If the update does not occur, this value may refer to an earlier revision.
    */
    pub versionControlRevision: *const ::std::os::raw::c_char,
    /** Version as a string, for example "PortAudio V19.5.0-devel, revision 1952M" */
    pub versionText: *const ::std::os::raw::c_char,
}
#[test]
fn bindgen_test_layout_PaVersionInfo() {
    assert_eq!(::std::mem::size_of::<PaVersionInfo>(), 32usize, concat!("Size of: ", stringify!(PaVersionInfo)));
    assert_eq!(::std::mem::align_of::<PaVersionInfo>(), 8usize, concat!("Alignment of ", stringify!(PaVersionInfo)));
    assert_eq!(
        unsafe { &(*(0 as *const PaVersionInfo)).versionMajor as *const _ as usize },
        0usize,
        concat!("Alignment of field: ", stringify!(PaVersionInfo), "::", stringify!(versionMajor))
    );
    assert_eq!(
        unsafe { &(*(0 as *const PaVersionInfo)).versionMinor as *const _ as usize },
        4usize,
        concat!("Alignment of field: ", stringify!(PaVersionInfo), "::", stringify!(versionMinor))
    );
    assert_eq!(
        unsafe { &(*(0 as *const PaVersionInfo)).versionSubMinor as *const _ as usize },
        8usize,
        concat!(
            "Alignment of field: ",
            stringify!(PaVersionInfo),
            "::",
            stringify!(versionSubMinor)
        )
    );
    assert_eq!(
        unsafe { &(*(0 as *const PaVersionInfo)).versionControlRevision as *const _ as usize },
        16usize,
        concat!(
            "Alignment of field: ",
            stringify!(PaVersionInfo),
            "::",
            stringify!(versionControlRevision)
        )
    );
    assert_eq!(
        unsafe { &(*(0 as *const PaVersionInfo)).versionText as *const _ as usize },
        24usize,
        concat!("Alignment of field: ", stringify!(PaVersionInfo), "::", stringify!(versionText))
    );
}
impl Clone for PaVersionInfo {
    fn clone(&self) -> Self {
        *self
    }
}
unsafe extern "C" {
    /** Retrieve version information for the currently running PortAudio build.
 @return A pointer to an immutable PaVersionInfo structure.

 @note This function can be called at any time. It does not require PortAudio
 to be initialized. The structure pointed to is statically allocated. Do not
 attempt to free it or modify it.

 @see PaVersionInfo, paMakeVersionNumber
 @version Available as of 19.5.0.
*/
    pub fn Pa_GetVersionInfo() -> *const PaVersionInfo;
}
/** Error codes returned by PortAudio functions.
 Note that with the exception of paNoError, all PaErrorCodes are negative.
*/
pub type PaError = ::std::os::raw::c_int;
pub const PaErrorCode_paNoError: PaErrorCode = 0;
pub const PaErrorCode_paNotInitialized: PaErrorCode = -10000;
pub const PaErrorCode_paUnanticipatedHostError: PaErrorCode = -9999;
pub const PaErrorCode_paInvalidChannelCount: PaErrorCode = -9998;
pub const PaErrorCode_paInvalidSampleRate: PaErrorCode = -9997;
pub const PaErrorCode_paInvalidDevice: PaErrorCode = -9996;
pub const PaErrorCode_paInvalidFlag: PaErrorCode = -9995;
pub const PaErrorCode_paSampleFormatNotSupported: PaErrorCode = -9994;
pub const PaErrorCode_paBadIODeviceCombination: PaErrorCode = -9993;
pub const PaErrorCode_paInsufficientMemory: PaErrorCode = -9992;
pub const PaErrorCode_paBufferTooBig: PaErrorCode = -9991;
pub const PaErrorCode_paBufferTooSmall: PaErrorCode = -9990;
pub const PaErrorCode_paNullCallback: PaErrorCode = -9989;
pub const PaErrorCode_paBadStreamPtr: PaErrorCode = -9988;
pub const PaErrorCode_paTimedOut: PaErrorCode = -9987;
pub const PaErrorCode_paInternalError: PaErrorCode = -9986;
pub const PaErrorCode_paDeviceUnavailable: PaErrorCode = -9985;
pub const PaErrorCode_paIncompatibleHostApiSpecificStreamInfo: PaErrorCode = -9984;
pub const PaErrorCode_paStreamIsStopped: PaErrorCode = -9983;
pub const PaErrorCode_paStreamIsNotStopped: PaErrorCode = -9982;
pub const PaErrorCode_paInputOverflowed: PaErrorCode = -9981;
pub const PaErrorCode_paOutputUnderflowed: PaErrorCode = -9980;
pub const PaErrorCode_paHostApiNotFound: PaErrorCode = -9979;
pub const PaErrorCode_paInvalidHostApi: PaErrorCode = -9978;
pub const PaErrorCode_paCanNotReadFromACallbackStream: PaErrorCode = -9977;
pub const PaErrorCode_paCanNotWriteToACallbackStream: PaErrorCode = -9976;
pub const PaErrorCode_paCanNotReadFromAnOutputOnlyStream: PaErrorCode = -9975;
pub const PaErrorCode_paCanNotWriteToAnInputOnlyStream: PaErrorCode = -9974;
pub const PaErrorCode_paIncompatibleStreamHostApi: PaErrorCode = -9973;
pub const PaErrorCode_paBadBufferPtr: PaErrorCode = -9972;
pub type PaErrorCode = ::std::os::raw::c_int;
unsafe extern "C" {
    /** Translate the supplied PortAudio error code into a human readable
 message.
*/
    pub fn Pa_GetErrorText(errorCode: PaError) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    /** Library initialization function - call this before using PortAudio.
 This function initializes internal data structures and prepares underlying
 host APIs for use.  With the exception of Pa_GetVersion(), Pa_GetVersionText(),
 and Pa_GetErrorText(), this function MUST be called before using any other
 PortAudio API functions.

 If Pa_Initialize() is called multiple times, each successful 
 call must be matched with a corresponding call to Pa_Terminate(). 
 Pairs of calls to Pa_Initialize()/Pa_Terminate() may overlap, and are not 
 required to be fully nested.

 Note that if Pa_Initialize() returns an error code, Pa_Terminate() should
 NOT be called.

 @return paNoError if successful, otherwise an error code indicating the cause
 of failure.

 @see Pa_Terminate
*/
    pub fn Pa_Initialize() -> PaError;
}
unsafe extern "C" {
    /** Library termination function - call this when finished using PortAudio.
 This function deallocates all resources allocated by PortAudio since it was
 initialized by a call to Pa_Initialize(). In cases where Pa_Initialise() has
 been called multiple times, each call must be matched with a corresponding call
 to Pa_Terminate(). The final matching call to Pa_Terminate() will automatically
 close any PortAudio streams that are still open.

 Pa_Terminate() MUST be called before exiting a program which uses PortAudio.
 Failure to do so may result in serious resource leaks, such as audio devices
 not being available until the next reboot.

 @return paNoError if successful, otherwise an error code indicating the cause
 of failure.
 
 @see Pa_Initialize
*/
    pub fn Pa_Terminate() -> PaError;
}
pub type PaDeviceIndex = ::std::os::raw::c_int;
pub type PaHostApiIndex = ::std::os::raw::c_int;
unsafe extern "C" {
    pub fn Pa_GetHostApiCount() -> PaHostApiIndex;
}
unsafe extern "C" {
    pub fn Pa_GetDefaultHostApi() -> PaHostApiIndex;
}
pub const PaHostApiTypeId_paInDevelopment: PaHostApiTypeId = 0;
pub const PaHostApiTypeId_paDirectSound: PaHostApiTypeId = 1;
pub const PaHostApiTypeId_paMME: PaHostApiTypeId = 2;
pub const PaHostApiTypeId_paASIO: PaHostApiTypeId = 3;
pub const PaHostApiTypeId_paSoundManager: PaHostApiTypeId = 4;
pub const PaHostApiTypeId_paCoreAudio: PaHostApiTypeId = 5;
pub const PaHostApiTypeId_paOSS: PaHostApiTypeId = 7;
pub const PaHostApiTypeId_paALSA: PaHostApiTypeId = 8;
pub const PaHostApiTypeId_paAL: PaHostApiTypeId = 9;
pub const PaHostApiTypeId_paBeOS: PaHostApiTypeId = 10;
pub const PaHostApiTypeId_paWDMKS: PaHostApiTypeId = 11;
pub const PaHostApiTypeId_paJACK: PaHostApiTypeId = 12;
pub const PaHostApiTypeId_paWASAPI: PaHostApiTypeId = 13;
pub const PaHostApiTypeId_paAudioScienceHPI: PaHostApiTypeId = 14;
pub type PaHostApiTypeId = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy)]
pub struct PaHostApiInfo {
    pub structVersion: ::std::os::raw::c_int,
    pub type_: PaHostApiTypeId,
    pub name: *const ::std::os::raw::c_char,
    pub deviceCount: ::std::os::raw::c_int,
    pub defaultInputDevice: PaDeviceIndex,
    pub defaultOutputDevice: PaDeviceIndex,
}
impl Clone for PaHostApiInfo {
    fn clone(&self) -> Self {
        *self
    }
}
unsafe extern "C" {
    pub fn Pa_GetHostApiInfo(hostApi: PaHostApiIndex) -> *const PaHostApiInfo;
}
unsafe extern "C" {
    pub fn Pa_HostApiTypeIdToHostApiIndex(type_: PaHostApiTypeId) -> PaHostApiIndex;
}
unsafe extern "C" {
    pub fn Pa_HostApiDeviceIndexToDeviceIndex(
        hostApi: PaHostApiIndex,
        hostApiDeviceIndex: ::std::os::raw::c_int,
    ) -> PaDeviceIndex;
}
#[repr(C)]
#[derive(Debug, Copy)]
pub struct PaHostErrorInfo {
    pub hostApiType: PaHostApiTypeId,
    pub errorCode: ::std::os::raw::c_long,
    pub errorText: *const ::std::os::raw::c_char,
}
impl Clone for PaHostErrorInfo {
    fn clone(&self) -> Self {
        *self
    }
}
unsafe extern "C" {
    pub fn Pa_GetLastHostErrorInfo() -> *const PaHostErrorInfo;
}
unsafe extern "C" {
    pub fn Pa_GetDeviceCount() -> PaDeviceIndex;
}
unsafe extern "C" {
    pub fn Pa_GetDefaultInputDevice() -> PaDeviceIndex;
}
unsafe extern "C" {
    pub fn Pa_GetDefaultOutputDevice() -> PaDeviceIndex;
}
pub type PaTime = f64;
pub type PaSampleFormat = ::std::os::raw::c_ulong;
#[repr(C)]
#[derive(Debug, Copy)]
pub struct PaDeviceInfo {
    pub structVersion: ::std::os::raw::c_int,
    pub name: *const ::std::os::raw::c_char,
    pub hostApi: PaHostApiIndex,
    pub maxInputChannels: ::std::os::raw::c_int,
    pub maxOutputChannels: ::std::os::raw::c_int,
    pub defaultLowInputLatency: PaTime,
    pub defaultLowOutputLatency: PaTime,
    pub defaultHighInputLatency: PaTime,
    pub defaultHighOutputLatency: PaTime,
    pub defaultSampleRate: f64,
}
impl Clone for PaDeviceInfo {
    fn clone(&self) -> Self {
        *self
    }
}
unsafe extern "C" {
    pub fn Pa_GetDeviceInfo(device: PaDeviceIndex) -> *const PaDeviceInfo;
}
#[repr(C)]
#[derive(Debug, Copy)]
pub struct PaStreamParameters {
    pub device: PaDeviceIndex,
    pub channelCount: ::std::os::raw::c_int,
    pub sampleFormat: PaSampleFormat,
    pub suggestedLatency: PaTime,
    pub hostApiSpecificStreamInfo: *mut ::std::os::raw::c_void,
}
impl Clone for PaStreamParameters {
    fn clone(&self) -> Self {
        *self
    }
}
unsafe extern "C" {
    pub fn Pa_IsFormatSupported(
        inputParameters: *const PaStreamParameters,
        outputParameters: *const PaStreamParameters,
        sampleRate: f64,
    ) -> PaError;
}
pub type PaStream = ::std::os::raw::c_void;
pub type PaStreamFlags = ::std::os::raw::c_ulong;
#[repr(C)]
#[derive(Debug, Copy)]
pub struct PaStreamCallbackTimeInfo {
    pub inputBufferAdcTime: PaTime,
    pub currentTime: PaTime,
    pub outputBufferDacTime: PaTime,
}
impl Clone for PaStreamCallbackTimeInfo {
    fn clone(&self) -> Self {
        *self
    }
}
pub type PaStreamCallbackFlags = ::std::os::raw::c_ulong;
pub type PaStreamCallback = ::std::option::Option<
    unsafe extern "C" fn(
        input: *const ::std::os::raw::c_void,
        output: *mut ::std::os::raw::c_void,
        frameCount: ::std::os::raw::c_ulong,
        timeInfo: *const PaStreamCallbackTimeInfo,
        statusFlags: PaStreamCallbackFlags,
        userData: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int,
>;
unsafe extern "C" {
    pub fn Pa_OpenStream(
        stream: *mut *mut PaStream,
        inputParameters: *const PaStreamParameters,
        outputParameters: *const PaStreamParameters,
        sampleRate: f64,
        framesPerBuffer: ::std::os::raw::c_ulong,
        streamFlags: PaStreamFlags,
        streamCallback: PaStreamCallback,
        userData: *mut ::std::os::raw::c_void,
    ) -> PaError;
}
unsafe extern "C" {
    pub fn Pa_OpenDefaultStream(
        stream: *mut *mut PaStream,
        numInputChannels: ::std::os::raw::c_int,
        numOutputChannels: ::std::os::raw::c_int,
        sampleFormat: PaSampleFormat,
        sampleRate: f64,
        framesPerBuffer: ::std::os::raw::c_ulong,
        streamCallback: PaStreamCallback,
        userData: *mut ::std::os::raw::c_void,
    ) -> PaError;
}
unsafe extern "C" {
    pub fn Pa_CloseStream(stream: *mut PaStream) -> PaError;
}
pub type PaStreamFinishedCallback =
    ::std::option::Option<unsafe extern "C" fn(userData: *mut ::std::os::raw::c_void)>;
unsafe extern "C" {
    pub fn Pa_SetStreamFinishedCallback(
        stream: *mut PaStream,
        streamFinishedCallback: PaStreamFinishedCallback,
    ) -> PaError;
}
unsafe extern "C" {
    pub fn Pa_StartStream(stream: *mut PaStream) -> PaError;
}
unsafe extern "C" {
    pub fn Pa_StopStream(stream: *mut PaStream) -> PaError;
}
unsafe extern "C" {
    pub fn Pa_AbortStream(stream: *mut PaStream) -> PaError;
}
unsafe extern "C" {
    pub fn Pa_IsStreamStopped(stream: *mut PaStream) -> PaError;
}
unsafe extern "C" {
    pub fn Pa_IsStreamActive(stream: *mut PaStream) -> PaError;
}
#[repr(C)]
#[derive(Debug, Copy)]
pub struct PaStreamInfo {
    pub structVersion: ::std::os::raw::c_int,
    pub inputLatency: PaTime,
    pub outputLatency: PaTime,
    pub sampleRate: f64,
}
impl Clone for PaStreamInfo {
    fn clone(&self) -> Self {
        *self
    }
}
unsafe extern "C" {
    pub fn Pa_GetStreamInfo(stream: *mut PaStream) -> *const PaStreamInfo;
}
unsafe extern "C" {
    pub fn Pa_GetStreamTime(stream: *mut PaStream) -> PaTime;
}
unsafe extern "C" {
    pub fn Pa_GetStreamCpuLoad(stream: *mut PaStream) -> f64;
}
unsafe extern "C" {
    pub fn Pa_ReadStream(
        stream: *mut PaStream,
        buffer: *mut ::std::os::raw::c_void,
        frames: ::std::os::raw::c_ulong,
    ) -> PaError;
}
unsafe extern "C" {
    pub fn Pa_WriteStream(
        stream: *mut PaStream,
        buffer: *const ::std::os::raw::c_void,
        frames: ::std::os::raw::c_ulong,
    ) -> PaError;
}
unsafe extern "C" {
    pub fn Pa_GetStreamReadAvailable(stream: *mut PaStream) -> ::std::os::raw::c_long;
}
unsafe extern "C" {
    pub fn Pa_GetStreamWriteAvailable(stream: *mut PaStream) -> ::std::os::raw::c_long;
}
unsafe extern "C" {
    pub fn Pa_GetSampleSize(format: PaSampleFormat) -> PaError;
}
unsafe extern "C" {
    pub fn Pa_Sleep(msec: ::std::os::raw::c_long);
}

